name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: Mediatek86

    - name: Build
      run: dotnet build --no-restore
      working-directory: Mediatek86

    - name: Publish
      working-directory: Mediatek86
      run: dotnet publish --configuration Release --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: windows-x64
        path: ./Mediatek86/publish/